# Generated by Django 6.0.6 on 2026-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=' ', verbose_name='Bio'),
        ),
    ]
